spring.application.name=backend

# Configuración de Servidor
server.port=8081

# Configuración de Base de Datos MySQL
# Asegúrate de crear la base de datos 'gestion_empleados' (o cambia el nombre aquí)
spring.datasource.url=jdbc:postgresql://localhost:5432/empleados
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' crea/actualiza las tablas automáticamente. Cambiar a 'validate' o 'none' en producción.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
